# golangci-lint configuration
# Run with: golangci-lint run

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters (explicitly listed for clarity)
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Static analysis checks
    - unused        # Check for unused code

    # Additional recommended linters
    - gofmt         # Check if code is gofmt-ed
    - goimports     # Check imports are sorted and formatted
    - misspell      # Find commonly misspelled words
    - bodyclose     # Check HTTP response body is closed
    - durationcheck # Check for duration multiplied with integer
    - errorlint     # Find issues with error wrapping
    - copyloopvar   # Check for pointers to loop variables (replaced exportloopref)
    - nilerr        # Find returning nil after checking error
    - noctx         # Find HTTP requests without context.Context
    - predeclared   # Find shadowing of predeclared identifiers
    - unconvert     # Remove unnecessary type conversions
    - whitespace    # Check for unnecessary whitespace

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/aidanlsb/raven
  misspell:
    locale: US
    # "cancelled" is used as a status value in the domain model
    ignore-words:
      - cancelled

issues:
  # Maximum issues count per one linter (0 = unlimited)
  max-issues-per-linter: 0
  # Maximum count of issues with the same text (0 = unlimited)
  max-same-issues: 0
  # Exclude some common patterns
  exclude-rules:
    # Test files can have longer functions and shadowing predeclared identifiers
    - path: _test\.go
      linters:
        - errcheck
        - predeclared

    # Deferred tx.Rollback() is idiomatic - it's a no-op after commit
    - text: "Error return value of `tx.Rollback`"
      linters:
        - errcheck

    # fmt.Sscanf parsing errors are often intentionally ignored when we have defaults
    - text: "Error return value of `fmt.Sscanf`"
      linters:
        - errcheck

    # fmt.Scanln for interactive prompts - errors are acceptable
    - text: "Error return value of `fmt.Scanln`"
      linters:
        - errcheck
