# golangci-lint configuration (v2)
# Run with: golangci-lint run

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Default linters (explicitly listed for clarity)
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Static analysis checks (includes gosimple)
    - unused        # Check for unused code

    # Additional recommended linters
    - misspell      # Find commonly misspelled words
    - bodyclose     # Check HTTP response body is closed
    - durationcheck # Check for duration multiplied with integer
    - errorlint     # Find issues with error wrapping
    - copyloopvar   # Check for pointers to loop variables
    - nilerr        # Find returning nil after checking error
    - noctx         # Find HTTP requests without context.Context
    - predeclared   # Find shadowing of predeclared identifiers
    - unconvert     # Remove unnecessary type conversions
    - whitespace    # Check for unnecessary whitespace

  settings:
    misspell:
      locale: US
      ignore-rules:
        - cancelled

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Test files can have longer functions and shadowing predeclared identifiers
      - path: _test\.go
        linters:
          - errcheck
          - predeclared

      # Deferred tx.Rollback() is idiomatic - it's a no-op after commit
      - text: "Error return value of `tx.Rollback`"
        linters:
          - errcheck

      # fmt.Sscanf parsing errors are often intentionally ignored when we have defaults
      - text: "Error return value of `fmt.Sscanf`"
        linters:
          - errcheck

      # fmt.Scanln for interactive prompts - errors are acceptable
      - text: "Error return value of `fmt.Scanln`"
        linters:
          - errcheck

      # Deferred lock.Release() is idiomatic - same pattern as defer f.Close()
      - text: "Error return value of `lock.Release`"
        linters:
          - errcheck

      # Internal SQLite code uses database/sql without context - acceptable for
      # local embedded database. Refactoring to context-aware calls is tracked separately.
      - path: internal/(index|query)/
        linters:
          - noctx

      # Test utilities use exec.Command without context - acceptable for tests
      - path: internal/testutil/
        linters:
          - noctx

      # QF (quick fix) suggestions from staticcheck are style hints, not errors
      - text: "^QF"
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt         # Check if code is gofmt-ed
    - goimports     # Check imports are sorted and formatted

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/aidanlsb/raven
