package commandimpl

import "github.com/aidanlsb/raven/internal/commandexec"

// RegisterAll registers canonical command handlers.
func RegisterAll(registry *commandexec.HandlerRegistry) {
	if registry == nil {
		return
	}

	registry.Register("new", HandleNew)
	registry.Register("upsert", HandleUpsert)
	registry.Register("add", HandleAdd)
	registry.Register("set", HandleSet)
	registry.Register("delete", HandleDelete)
	registry.Register("move", HandleMove)
	registry.Register("reclassify", HandleReclassify)
	registry.Register("update", HandleUpdate)
	registry.Register("edit", HandleEdit)
	registry.Register("import", HandleImport)
	registry.Register("init", HandleInit)
	registry.Register("reindex", HandleReindex)
	registry.Register("check", HandleCheck)
	registry.Register("check_fix", HandleCheckFix)
	registry.Register("check create-missing", HandleCheckCreateMissing)
	registry.Register("daily", HandleDaily)
	registry.Register("date", HandleDate)
	registry.Register("version", HandleVersion)
	registry.Register("config_show", HandleConfigShow)
	registry.Register("config_init", HandleConfigInit)
	registry.Register("config_set", HandleConfigSet)
	registry.Register("config_unset", HandleConfigUnset)
	registry.Register("vault_list", HandleVaultList)
	registry.Register("vault_current", HandleVaultCurrent)
	registry.Register("vault_path", HandleVaultPath)
	registry.Register("vault_use", HandleVaultUse)
	registry.Register("vault_add", HandleVaultAdd)
	registry.Register("vault_remove", HandleVaultRemove)
	registry.Register("vault_pin", HandleVaultPin)
	registry.Register("vault_clear", HandleVaultClear)
	registry.Register("vault_config_show", HandleVaultConfigShow)
	registry.Register("vault_config_auto_reindex_set", HandleVaultConfigAutoReindexSet)
	registry.Register("vault_config_auto_reindex_unset", HandleVaultConfigAutoReindexUnset)
	registry.Register("vault_config_protected_prefixes_list", HandleVaultConfigProtectedPrefixesList)
	registry.Register("vault_config_protected_prefixes_add", HandleVaultConfigProtectedPrefixesAdd)
	registry.Register("vault_config_protected_prefixes_remove", HandleVaultConfigProtectedPrefixesRemove)
	registry.Register("vault_config_directories_get", HandleVaultConfigDirectoriesGet)
	registry.Register("vault_config_directories_set", HandleVaultConfigDirectoriesSet)
	registry.Register("vault_config_directories_unset", HandleVaultConfigDirectoriesUnset)
	registry.Register("vault_config_capture_get", HandleVaultConfigCaptureGet)
	registry.Register("vault_config_capture_set", HandleVaultConfigCaptureSet)
	registry.Register("vault_config_capture_unset", HandleVaultConfigCaptureUnset)
	registry.Register("vault_config_deletion_get", HandleVaultConfigDeletionGet)
	registry.Register("vault_config_deletion_set", HandleVaultConfigDeletionSet)
	registry.Register("vault_config_deletion_unset", HandleVaultConfigDeletionUnset)
	registry.Register("vault_stats", HandleVaultStats)
	registry.Register("search", HandleSearch)
	registry.Register("read", HandleRead)
	registry.Register("open", HandleOpen)
	registry.Register("query", HandleQuery)
	registry.Register("query_saved_list", HandleQuerySavedList)
	registry.Register("query_saved_get", HandleQuerySavedGet)
	registry.Register("query_saved_set", HandleQuerySavedSet)
	registry.Register("query_saved_remove", HandleQuerySavedRemove)
	registry.Register("docs", HandleDocs)
	registry.Register("docs_fetch", HandleDocsFetch)
	registry.Register("docs_list", HandleDocsList)
	registry.Register("docs_search", HandleDocsSearch)
	registry.Register("skill_list", HandleSkillList)
	registry.Register("skill_sync", HandleSkillSync)
	registry.Register("skill_remove", HandleSkillRemove)
	registry.Register("skill_doctor", HandleSkillDoctor)
	registry.Register("backlinks", HandleBacklinks)
	registry.Register("outlinks", HandleOutlinks)
	registry.Register("resolve", HandleResolve)
	registry.Register("schema", HandleSchema)
	registry.Register("schema_validate", HandleSchemaValidate)
	registry.Register("schema_add_type", HandleSchemaAddType)
	registry.Register("schema_add_trait", HandleSchemaAddTrait)
	registry.Register("schema_add_field", HandleSchemaAddField)
	registry.Register("schema_update_type", HandleSchemaUpdateType)
	registry.Register("schema_update_trait", HandleSchemaUpdateTrait)
	registry.Register("schema_update_field", HandleSchemaUpdateField)
	registry.Register("schema_remove_type", HandleSchemaRemoveType)
	registry.Register("schema_remove_trait", HandleSchemaRemoveTrait)
	registry.Register("schema_remove_field", HandleSchemaRemoveField)
	registry.Register("schema_rename_type", HandleSchemaRenameType)
	registry.Register("schema_rename_field", HandleSchemaRenameField)
	registry.Register("schema_template_list", HandleSchemaTemplateList)
	registry.Register("schema_template_get", HandleSchemaTemplateGet)
	registry.Register("schema_template_set", HandleSchemaTemplateSet)
	registry.Register("schema_template_remove", HandleSchemaTemplateRemove)
	registry.Register("schema_template_bind", HandleSchemaTemplateBind)
	registry.Register("schema_template_unbind", HandleSchemaTemplateUnbind)
	registry.Register("schema_template_default", HandleSchemaTemplateDefault)
	registry.Register("template_list", HandleTemplateList)
	registry.Register("template_write", HandleTemplateWrite)
	registry.Register("template_delete", HandleTemplateDelete)
}
