package commandimpl

import "github.com/aidanlsb/raven/internal/commandexec"

// RegisterAll registers canonical command handlers.
func RegisterAll(registry *commandexec.HandlerRegistry) {
	if registry == nil {
		return
	}

	registry.Register("new", HandleNew)
	registry.Register("upsert", HandleUpsert)
	registry.Register("add", HandleAdd)
	registry.Register("set", HandleSet)
	registry.Register("delete", HandleDelete)
	registry.Register("move", HandleMove)
	registry.Register("reclassify", HandleReclassify)
	registry.Register("update", HandleUpdate)
	registry.Register("edit", HandleEdit)
	registry.Register("import", HandleImport)
	registry.Register("init", HandleInit)
	registry.Register("reindex", HandleReindex)
	registry.Register("check", HandleCheck)
	registry.Register("check_fix", HandleCheckFix)
	registry.Register("check create-missing", HandleCheckCreateMissing)
	registry.Register("daily", HandleDaily)
	registry.Register("date", HandleDate)
	registry.Register("version", HandleVersion)
	registry.Register("config_show", HandleConfigShow)
	registry.Register("config_init", HandleConfigInit)
	registry.Register("config_set", HandleConfigSet)
	registry.Register("config_unset", HandleConfigUnset)
	registry.Register("vault_list", HandleVaultList)
	registry.Register("vault_current", HandleVaultCurrent)
	registry.Register("vault_path", HandleVaultPath)
	registry.Register("vault_use", HandleVaultUse)
	registry.Register("vault_add", HandleVaultAdd)
	registry.Register("vault_remove", HandleVaultRemove)
	registry.Register("vault_pin", HandleVaultPin)
	registry.Register("vault_clear", HandleVaultClear)
	registry.Register("vault_stats", HandleVaultStats)
	registry.Register("search", HandleSearch)
	registry.Register("read", HandleRead)
	registry.Register("open", HandleOpen)
	registry.Register("query", HandleQuery)
	registry.Register("query_add", HandleQueryAdd)
	registry.Register("query_remove", HandleQueryRemove)
	registry.Register("docs", HandleDocs)
	registry.Register("docs_fetch", HandleDocsFetch)
	registry.Register("docs_list", HandleDocsList)
	registry.Register("docs_search", HandleDocsSearch)
	registry.Register("skill_list", HandleSkillList)
	registry.Register("skill_install", HandleSkillInstall)
	registry.Register("skill_remove", HandleSkillRemove)
	registry.Register("skill_doctor", HandleSkillDoctor)
	registry.Register("backlinks", HandleBacklinks)
	registry.Register("outlinks", HandleOutlinks)
	registry.Register("resolve", HandleResolve)
	registry.Register("schema", HandleSchema)
	registry.Register("schema_validate", HandleSchemaValidate)
	registry.Register("schema_add_type", HandleSchemaAddType)
	registry.Register("schema_add_trait", HandleSchemaAddTrait)
	registry.Register("schema_add_field", HandleSchemaAddField)
	registry.Register("schema_update_type", HandleSchemaUpdateType)
	registry.Register("schema_update_trait", HandleSchemaUpdateTrait)
	registry.Register("schema_update_field", HandleSchemaUpdateField)
	registry.Register("schema_remove_type", HandleSchemaRemoveType)
	registry.Register("schema_remove_trait", HandleSchemaRemoveTrait)
	registry.Register("schema_remove_field", HandleSchemaRemoveField)
	registry.Register("schema_rename_type", HandleSchemaRenameType)
	registry.Register("schema_rename_field", HandleSchemaRenameField)
	registry.Register("schema_template_list", HandleSchemaTemplateList)
	registry.Register("schema_template_get", HandleSchemaTemplateGet)
	registry.Register("schema_template_set", HandleSchemaTemplateSet)
	registry.Register("schema_template_remove", HandleSchemaTemplateRemove)
	registry.Register("schema_template_bind", HandleSchemaTemplateBind)
	registry.Register("schema_template_unbind", HandleSchemaTemplateUnbind)
	registry.Register("schema_template_default", HandleSchemaTemplateDefault)
	registry.Register("template_list", HandleTemplateList)
	registry.Register("template_write", HandleTemplateWrite)
	registry.Register("template_delete", HandleTemplateDelete)
	registry.Register("workflow_list", HandleWorkflowList)
	registry.Register("workflow_add", HandleWorkflowAdd)
	registry.Register("workflow_scaffold", HandleWorkflowScaffold)
	registry.Register("workflow_remove", HandleWorkflowRemove)
	registry.Register("workflow_validate", HandleWorkflowValidate)
	registry.Register("workflow_show", HandleWorkflowShow)
	registry.Register("workflow_step_add", HandleWorkflowStepAdd)
	registry.Register("workflow_step_batch", HandleWorkflowStepBatch)
	registry.Register("workflow_step_update", HandleWorkflowStepUpdate)
	registry.Register("workflow_step_remove", HandleWorkflowStepRemove)
	registry.Register("workflow_run", HandleWorkflowRun)
	registry.Register("workflow_continue", HandleWorkflowContinue)
	registry.Register("workflow_runs_list", HandleWorkflowRunsList)
	registry.Register("workflow_runs_step", HandleWorkflowRunsStep)
	registry.Register("workflow_runs_prune", HandleWorkflowRunsPrune)
}
